name: uroscan
channels:
  - dranew
  - bioconda
  - conda-forge
  - defaults
  - r
dependencies:
  - r-base=3.4.1
  - rsem=1.3.0
  - bowtie2=2.3.3.1
  - salmon=0.13.1
  - star=2.5.3a
  - rseqc=2.6.4
  - r-knitr=1.16
  - vladsaveliev::r-kableextra=0.9.0
  - r-jsonlite=1.4
  - r-dplyr=0.7.4
  - r-reshape=0.8.6
  - r-ggplot2=2.2.0
  - r-cowplot=0.9.1
  - r-gridextra=2.2.1
  - r-ranger=0.7.0
