name: uroscan
channels:
  - dranew
  - bioconda
  - conda-forge
  - defaults
  - r
dependencies:
#  - r-base=3.4.1
#  - rsem=1.3.0
#  - bowtie2=2.3.3.1
#  - salmon=0.13.1
#  - star=2.5.3a
#  - rseqc=2.6.4
#  - r-knitr=1.16
# - vladsaveliev::r-kableextra=0.9.0
#  - r-jsonlite=1.4
#  - r-dplyr=0.7.4
#  - r-reshape=0.8.6
#  - r-ggplot2=2.2.0
#  - r-cowplot=0.9.1
#  - r-gridextra=2.2.1
#  - r-ranger=0.7.0

  - _r-mutex=1.0.1
  - bioconductor-biobase=2.40.0
  - bioconductor-biocgenerics=0.26.0
  - bioconductor-ebseq=1.20.0
  - boost=1.64.0
  - boost-cpp=1.64.0
  - bowtie2=2.3.3.1
  - bx-python=0.8.9
  - bzip2=1.0.8
  - ca-certificates=2021.5.30
  - cairo=1.14.12
  - certifi=2019.11.28
  - curl=7.61.0
  - cython=0.29.15
  - fontconfig=2.13.1
  - freetype=2.10.4
  - gettext=0.19.8.1
  - glib=2.56.2
  - graphite2=1.3.13
  - gsl=2.2.1
  - harfbuzz=1.9.0
  - icu=58.2
  - jemalloc=5.2.1
  - jpeg=9d
  - krb5=1.14.6
  - libblas=3.8.0
  - libboost=1.73.0
  - libcblas=3.8.0
  - libcxx=11.1.0
  - libdeflate=1.0
  - libffi=3.2.1
  - libgcc=4.8.5
  - libgfortran
  - libiconv=1.16
  - liblapack=3.8.0
  - libopenblas=0.3.7
  - libpng=1.6.37
  - libssh2=1.8.0
  - libtiff=4.2.0
  - libwebp-base=1.2.0
  - libxcb=1.13
  - libxml2=2.9.9
  - lz4-c=1.9.3
  - lzo=2.10
  - ncurses=6.2
  - numpy=1.16.5
  - openssl=1.0.2u
  - pandoc=2.14.0.1
  - pango=1.40.14
  - pcre=8.44
  - perl=5.22.0.1
  - perl-module-build=0.4224
  - pip=20.1.1
  - pixman=0.34.0
  - pthread-stubs=0.4
  - pysam=0.15.3
  - python=2.7.15
  - python-lzo=1.12
  - python_abi=2.7
  - r-assertthat=0.2.0
  - r-backports=1.1.2
  - r-base=3.4.1
  - r-base64enc=0.1_3
  - r-bh=1.66.0_1
  - r-bibtex=0.4.2
  - r-bindr=0.1.1
  - r-bindrcpp=0.2.2
  - r-bitops=1.0_6
  - r-blockmodeling=0.3.1
  - r-catools=1.17.1.1
  - r-cli=1.0.0
  - r-codetools=0.2_15
  - r-colorspace=1.3_2
  - r-cowplot=0.9.1
  - r-crayon=1.3.4
  - r-curl=3.2
  - r-digest=0.6.18
  - r-doparallel=1.0.11
  - r-dorng=1.7.1
  - r-dplyr=0.7.4
  - r-evaluate=0.11
  - r-foreach=1.4.4
  - r-gdata=2.18.0
  - r-ggplot2=2.2.0
  - r-glue=1.3.0
  - r-gplots=3.0.1
  - r-gridextra=2.2.1
  - r-gtable=0.2.0
  - r-gtools=3.8.1
  - r-highr=0.7
  - r-hms=0.4.2
  - r-htmltools=0.3.6
  - r-httr=1.3.1
  - r-iterators=1.0.10
  - r-jsonlite=1.4
  - vladsaveliev::r-kableextra=0.9.0
  - r-kernsmooth=2.23_15
  - r-knitr=1.16
  - r-labeling=0.3
  - r-lattice=0.20_35
  - r-lazyeval=0.2.1
  - r-magrittr=1.5
  - r-markdown=0.8
  - r-mass=7.3_50
  - r-matrix=1.2_14
  - r-mime=0.5
  - r-munsell=0.5.0
  - r-openssl=1.0.2
  - r-pkgconfig=2.0.2
  - r-pkgmaker=0.27
  - r-plogr=0.2.0
  - r-plyr=1.8.4
  - r-praise=1.0.0
  - r-r6=2.2.2
  - r-ranger=0.7.0
  - r-rcolorbrewer=1.1_2
  - r-rcpp=1.0.0
  - r-readr=1.1.1
  - r-registry=0.5
  - r-reshape=0.8.6
  - r-reshape2=1.4.3
  - r-rlang=0.3.0.1
  - r-rmarkdown=1.9
  - r-rngtools=1.3.1
  - r-rprojroot=1.3_2
  - r-rstudioapi=0.7
  - r-rvest=0.3.2
  - r-scales=1.0.0
  - r-selectr=0.4_1
  - r-stringi=1.2.4
  - r-stringr=1.3.1
  - r-testthat=2.0.1
  - r-tibble=1.3.3
  - r-viridislite=0.3.0
  - r-withr=2.1.2
  - r-xml2=1.2.0
  - r-xtable=1.8_3
  - r-yaml=2.2.0
  - readline=7.0
  - rsem=1.3.0
  - rseqc=2.6.4
  - salmon=0.13.1
  - samtools=1.3
  - setuptools=44.0.0
  - six=1.16.0
  - sqlite=3.28.0
  # - star=2.5.3a
  - tbb=2021.2.0
  - tk=8.6.10
  - wheel=0.36.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.9
